language: objective-c
osx_image: xcode7.2
cache:
  - cocoapods
env:
  global:
  - WORKSPACE="RealmMapper.xcworkspace"
  - SCHEME="RealmMapper"
  - SDK="iphonesimulator9.2"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 6 Plus"   POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6s Plus"  POD_LINT="YES"
before_install:
  - set -o pipefail
  - gem install xcpretty
  - pod install
script:
  # test Debug
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration Debug build test | xcpretty -c
  # test Release
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration ReleaseTest build test | xcpretty -c
  # pod lint if needs
  - if [ $POD_LINT == "YES" ]; then pod lib lint --quick; fi
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
