language: objective-c
osx_image: xcode7.2
cache:
  - bundler
  - cocoapods
env:
  global:
  - WORKSPACE="RealmMapper.xcworkspace"
  - PROJECT="RealmMapper.xcodeproj"
  - IOS_SCHEME="RealmMapper"
  - IOS_SDK="iphonesimulator9.2"
  - CONFIGURATION="ReleaseTest"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 5S"          SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"    
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - set -o pipefail
  - rvm use 2.2.4  
  - gem install bundler --no-rdoc --no-ri 
  - bundle install --path=vendor/bundle --without=documentation
  - bundler exec pod install
script:
  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration Debug test | bundler exec xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration Debug build | bundler exec xcpretty -c;
    fi
  # Build Framework in ReleaseTest and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration ReleaseTest test | bundler exec xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES -configuration ReleaseTest build | bundler exec xcpretty -c;
    fi
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      bundler exec pod lib lint --quick;
    fi
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
