language: objective-c
osx_image: xcode7.2
cache:
  - cocoapods
env:
  global:
  - WORKSPACE="RealmMapper.xcworkspace"
  - PROJECT="RealmMapper.xcodeproj"
  - IOS_SCHEME="RealmMapper"
  - IOS_SDK="iphonesimulator9.2"
  - CONFIGURATION="ReleaseTest"
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 6 Plus"   POD_LINT="NO"
    - DESTINATION="OS=9.2,name=iPhone 6s Plus"  POD_LINT="YES"
before_install:
  - set -o pipefail
  - gem install xcpretty
  - pod install
script:
  # Build Framework in Debug and Run Tests if specified
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration Debug test | xcpretty -c
  # Build Framework in ReleaseTest and Run Tests if specified
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration ReleaseTest test | xcpretty -c
  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick
    fi
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
